server:
  port: 8081
  servlet:
    context-path: /petsmatch-auth

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

spring:
  application:
    name: AuthService

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
  